# ---- Build React app ----
FROM node:20-alpine AS builder

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/. .

RUN npm run build

# ---- Serve with Nginx ----
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY client/Docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80